// import type { Metadata } from "next";
// import { Poppins as FontSans } from "next/font/google";
// import "@/app/styles/globals.css";

// const fontSans = FontSans({
// 	subsets: ["latin"],
// 	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// 	variable: "--font-sans",
// });
// export const metadata: Metadata = {
// 	title: "Abdul Ahad | Portfolio",
// 	description: "Generated by create next app",
// };

// export default function RootLayout({
// 	children,
// }: Readonly<{
// 	children: React.ReactNode;
// }>) {
// 	return (
// 		<html lang="en">
// 			<body className={fontSans.variable}>{children}</body>
// 		</html>
// 	);
// }


import type { Metadata } from "next";
import { Poppins as FontSans } from "next/font/google";
import "@/app/styles/globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Abdul Ahad | Portfolio",
  description: "3D Web Developer & Full Stack Engineer",
  icons: {
    icon: "/hacker.jpeg", // 👈 Tab icon
    shortcut: "/hacker.jpeg", // 👈 Shortcut icon
    apple: "/hacker.jpeg", // 👈 Apple devices
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.variable}>{children}</body>
    </html>
  );
}